backend:
  name: git-gateway
  branch: master

media_folder: "_site/img/remote"
public_folder: "/img/remote"

collections:
  -name: "posts"
  label: "Posts"
  folder: "posts"
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - { label: "Layout", name: "layout", widget: "" }
